- hosts: all
  vars:
   pkgs:
    - hadoop-1.2.1-1.x86_64.rpm
    - jdk-8u171-linux-x64.rpm
   rule:
    - http
    - https
  vars_prompt:
   name: dir_name
   private: no
   prompt: "Enter directory  name:"
  tasks:
  - name: installing openjdk & hadoop
    command: rpm -ivh "{{item}}" --force
    loop: "{{pkgs}}"
  - name: edit the hdfs-site.xml
    lineinfile:
     path: /etc/hadoop/hdfs-site.xml
     insertafter: "<configuration>"
     line: "<property>
      \n<name>dfs.name.dir</name>
      \n<value>/{{dir_name}}</value>
      \n</property>"
  - name: edit the core-site.xml
    lineinfile:
     path: /etc/hadoop/core-site.xml
     insertafter: "<configuration>"
     line: "<property>
      \n<name>fs.default.name</name>
      \n<value>hdfs://192.168.43.159:9001</value>
      \n</property>"
  - firewalld:
     service: "{{item}}"
     permanent: yes
     state: disabled
     immediate: yes
    loop: "{{rule}}"
  - file:
     name: "{{dir_name}}"
     path: /
     owner: root
     group: root
     mode: '0754'
     state: directory
  - name: format the namenode directory
    command: "hadoop namenode -format"
  - name: starting namenode services
    command: "hadoop-daemon.sh start namenode"

